python -u ./ner.py \
--architecture sotfmax \
--bert_config_file ./bert-base-chinese \
--train_file ./data/train.txt \
--dev_file ./data/dev.txt \
--test_file ./data/test.txt \
--output_dir ./output \
--max_len 200 \
--tags_file ./data/tags.txt \
--train_batch_size 25 \
--learning_rate 5e-5 \
--epoch 30 \
--test_batch_size 1 \
--tensorboard ./output/logs \
--dropout 0.5 \
--seed 1
